#!/bin/zsh

install_brew
install_vscode
install_python
install_tmux
Install_i3

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
