#!/usr/env zsh
echo "\nStarting installation of the dotfiles.\n"
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="zsh, gitconfig"
fi
echo "STOW_FOLDERS contains $STOW_FOLDERS"

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi
echo "DOTFILES contain $DOTFILES"

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install