#!/bin/zsh

cp ~/.dotfiles/vscode/vscode_settings ~/Library/Application\ Support/Code/User/settings.json
cp ~/.dotfiles/vscode/vscode_keybindings ~/Library/Application\ Support/Code/User/keybindings.jsons