#!usr/bin/zsh

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi
echo "DOTFILES contain $DOTFILES"

mkdir $DOTFILES/vscode/archive

cp ~/Library/Application\ Support/Code/User/settings.json ~/.dotfiles/vscode/archive/vscode_settings
cp ~/Library/Application\ Support/Code/User/keybindings.json ~/.dotfiles/vscode/archive/vscode_keybindings
cp ~/Library/Application\ Support/Code/User/snippets/` ~/.dotfiles/vscode/archive